### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "JUNIOR",
  "developerSkillType": "BACK_END",
  "experienceYears": ,
  "memberId": "Moowon",
  "name": "joowon",
  "age": 24

}